# Generated by Django 4.2.7 on 2024-04-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_solved', models.BooleanField(default=False)),
                ('solution_my', models.TextField(blank=True, null=True)),
                ('solution_pd', models.TextField(blank=True, null=True)),
                ('testcase', models.TextField(blank=True, null=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_to', to='sql_problems.difficulty')),
                ('tags', models.ManyToManyField(to='sql_problems.tag')),
            ],
        ),
    ]
