# Generated by Django 5.0.1 on 2024-04-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='problems',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
