# Generated by Django 5.0.1 on 2024-04-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0002_remove_tag_problems_delete_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_solved', models.BooleanField(default=False)),
                ('solution', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='python_problems.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='problems',
            field=models.ManyToManyField(to='python_problems.problem'),
        ),
    ]
