# Generated by Django 5.0.1 on 2024-04-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0003_problem_tag_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='problems',
        ),
    ]
