# Generated by Django 5.0.1 on 2024-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0004_remove_tag_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='testcase',
            field=models.TextField(blank=True, null=True),
        ),
    ]
