# Generated by Django 5.0.1 on 2024-04-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0005_problem_testcase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
    ]
