# Generated by Django 4.2.7 on 2024-04-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
