# Generated by Django 4.2.7 on 2024-04-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0007_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_to', to='python_problems.difficulty'),
            preserve_default=False,
        ),
    ]
