# Generated by Django 4.2.7 on 2024-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0008_problem_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'Difficulties'},
        ),
    ]
