# Generated by Django 4.2.7 on 2024-05-08 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0009_alter_difficulty_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Complexities',
            },
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_to1', to='python_problems.difficulty'),
        ),
    ]
