# Generated by Django 4.2.7 on 2024-05-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0010_complexity_alter_difficulty_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='space_complexity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_to3', to='python_problems.complexity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='time_complexity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_to2', to='python_problems.complexity'),
            preserve_default=False,
        ),
    ]
