# Generated by Django 4.2.7 on 2024-05-26 16:10

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0012_alter_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]