# Generated by Django 4.2.7 on 2024-06-07 21:25

from django.db import migrations
import python_problems.models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0014_populate_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=python_problems.models.NonStrippingTextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=python_problems.models.NonStrippingTextField(blank=True, null=True),
        ),
    ]
