# Generated by Django 4.2.7 on 2024-06-17 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('python_problems', '0019_problem_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(blank=True, null=True)),
                ('testcase', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions_language', to='python_problems.language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions_problem', to='python_problems.problem')),
                ('space_complexity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solutions_space_complexity', to='python_problems.complexity')),
                ('time_complexity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solutions_time_complexity', to='python_problems.complexity')),
            ],
        ),
    ]
