# Generated by Django 4.2.7 on 2024-06-17 20:50

from django.db import migrations


def migrate_data(apps, _):
    Problem = apps.get_model('python_problems', 'Problem')
    Solution = apps.get_model('python_problems', 'Solution')
    Language = apps.get_model('python_problems', 'Language')

    python_language = Language.objects.get(pk=1)


    for problem in Problem.objects.all():
        Solution.objects.create(
            solution=problem.solution,
            testcase=problem.testcase,
            created_at=problem.created_at,
            updated_at=problem.updated_at,
            language=python_language,
            owner=problem.owner,
            problem=problem,
            time_complexity=problem.time_complexity,
            space_complexity=problem.space_complexity
        )


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0021_populate_language'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
