# Generated by Django 4.2.7 on 2024-06-17 21:26

from django.db import migrations, models


def migrate_data(apps, _):
    Problem = apps.get_model('python_problems', 'Problem')
    Solution = apps.get_model('python_problems', 'Solution')
    Language = apps.get_model('python_problems', 'Language')


    for solution in Solution.objects.all():
        problem = solution.problem
        solution.created_at = problem.created_at
        solution.updated_at = problem.created_at
        solution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0022_migrate_data_to_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=False, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='updated_at',
            field=models.DateTimeField(auto_now=False, null=True),
        ),
        migrations.RunPython(migrate_data),
        migrations.AlterField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
