# Generated by Django 4.2.7 on 2024-06-17 21:32

from django.db import migrations, models


def migrate_data(apps, _):
    Problem = apps.get_model('python_problems', 'Problem')
    Solution = apps.get_model('python_problems', 'Solution')
    Language = apps.get_model('python_problems', 'Language')


    for problem in Problem.objects.all():
        problem.updated_at = problem.created_at
        problem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0023_alter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=False, null=True),
        ),
        migrations.RunPython(migrate_data),
        migrations.AlterField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
