# Generated by Django 4.2.7 on 2024-06-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0024_alter_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='problems',
            field=models.ManyToManyField(related_name='languages_problem', through='python_problems.Solution', to='python_problems.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='languages',
            field=models.ManyToManyField(related_name='problems_laguage', through='python_problems.Solution', to='python_problems.language'),
        ),
    ]
