# Generated by Django 4.2.7 on 2024-06-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0025_language_problems_problem_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solutions',
            field=models.ManyToManyField(related_name='problem_solutions', to='python_problems.solution'),
        ),
    ]
