# Generated by Django 4.2.7 on 2024-06-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0026_problem_solutions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(fields=('problem', 'language'), name='unique_solution_per_problem_language'),
        ),
    ]
