# Generated by Django 4.2.7 on 2024-06-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0029_alter_problem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='space_complexity',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='time_complexity',
        ),
    ]
