# Generated by Django 4.2.7 on 2024-06-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0030_remove_problem_space_complexity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solutions',
        ),
    ]
