# Generated by Django 4.2.7 on 2024-06-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0031_remove_problem_languages_remove_problem_solutions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solution',
            name='unique_solution_per_problem_language',
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(fields=('problem', 'language', 'owner'), name='unique_solution_per_problem_language_owner'),
        ),
    ]
