# Generated by Django 4.2.7 on 2024-06-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0032_remove_solution_unique_solution_per_problem_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='problems',
        ),
    ]
