# Generated by Django 4.2.7 on 2024-06-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0034_alter_solution_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions_per_language', to='python_problems.language'),
        ),
    ]
