# Generated by Django 4.2.7 on 2024-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0035_alter_solution_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='testcase',
            field=models.TextField(blank=True, help_text='Provide each testcase in `()` in a new like (function(agrs), solution)', null=True),
        ),
    ]
