# Generated by Django 4.2.7 on 2025-03-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0036_alter_solution_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='solution',
            new_name='source_code',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='testcase',
            new_name='test_case',
        ),
        migrations.AlterField(
            model_name='solution',
            name='test_case',
            field=models.TextField(blank=True, help_text='Format test cases as `([class.?]function(args), expected_result)`, one per line. Example: (reverse_string("hello"), "olleh")', null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='space_complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solution_space_complexity', to='python_problems.complexity'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time_complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solution_time_complexity', to='python_problems.complexity'),
        ),
        migrations.RemoveConstraint(
            model_name='solution',
            name='unique_solution_per_problem_language_owner',
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(fields=('problem', 'language', 'owner'), name='unique_user_solution_per_problem_and_language'),
        ),
    ]
