# Generated by Django 4.2.7 on 2025-03-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0037_remove_solution_unique_solution_per_problem_language_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_problems.language'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_problems.problem'),
        ),
    ]
