# Generated by Django 4.2.7 on 2026-03-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0039_rename_test_case_solution_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
