# Generated by Django 5.2.12 on 2026-04-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0040_alter_problem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='method_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('function', 'Function Problem'), ('class', 'Class Design Problem')], default='function', max_length=20),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='python_problems.problem')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
