# Generated by Django 5.2.12 on 2026-04-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0041_problem_method_name_problem_problem_type_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='argument_names',
            field=models.JSONField(blank=True, help_text='Optional argument labels for positional inputs, e.g. ["nums", "target"]', null=True),
        ),
    ]
