# Generated by Django 5.2.12 on 2026-05-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0042_problem_argument_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='problems', to='python_problems.difficulty'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='method_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('function', 'Function'), ('class', 'Class Design'), ('binary_tree', 'Binary Tree'), ('linked_list', 'Linked List')], default='function', max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='source_code',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='space_complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solutions_by_space_complexity', to='python_problems.complexity'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time_complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solutions_by_time_complexity', to='python_problems.complexity'),
        ),
    ]
