# Generated by Django 5.2.12 on 2026-05-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0044_remove_solution_unique_user_solution_per_problem_and_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddField(
            model_name='solution',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='python_problems.problem'),
        ),
    ]
