# Generated by Django 5.2.12 on 2026-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0045_alter_solution_options_solution_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
