# Generated by Django 5.2.12 on 2026-05-04 20:51

import django.db.models.deletion
import python_problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0046_testcase_explanation_alter_solution_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='space_complexity',
            field=models.ForeignKey(default=python_problems.models.Solution.get_default_complexity, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solutions_by_space_complexity', to='python_problems.complexity'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time_complexity',
            field=models.ForeignKey(default=python_problems.models.Solution.get_default_complexity, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solutions_by_time_complexity', to='python_problems.complexity'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
