# Generated by Django 5.2.12 on 2026-05-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0047_alter_solution_space_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='comparison_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('unordered', 'Unordered (unique)'), ('multiset', 'Unordered (with duplicates)')], default='exact', max_length=20),
        ),
    ]
