# Generated by Django 5.2.12 on 2026-05-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0049_testcase_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Problem metadata', null=True),
        ),
    ]
