# Generated by Django 5.2.12 on 2026-05-20 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0050_problem_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCase',
            new_name='ProblemTestCase',
        ),
    ]
