# Generated by Django 5.2.12 on 2026-08-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0051_rename_testcase_problemtestcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='comparison_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('unordered', 'Unordered (unique)'), ('multiset', 'Unordered (with duplicates)'), ('validator', 'Custom problem validator.')], default='exact', max_length=20),
        ),
    ]
