# Generated by Django 4.2.7 on 2024-06-16 22:03

from django.db import migrations, models



def migrate_data(apps, _):
    Problem = apps.get_model('python_problems', 'Problem')
    Solution = apps.get_model('python_problems', 'Solution')
    Language = apps.get_model('python_problems', 'Language')

    python_language = Language.objects.get(name='Python')

    
    for problem in Problem.objects.all():
        solution = problem
        

    for solution in Solution.objects.all():
        problem = solution.problem
        solution.language = python_language
        solution.created_at = problem.created_at
        solution.updated_at = problem.updated_at
        solution.save()

class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0020_populate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(migrate_data),
        migrations.AlterField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]










    
