# Generated by Django 4.2.7 on 2024-06-16 22:05


from django.db import migrations


def create_languages(apps, schema_editor):
    Language = apps.get_model('python_problems', 'Language')
    languages = ['Python', 'JavaScript']
    for lang in languages:
        Language.objects.create(name=lang)


class Migration(migrations.Migration):

    dependencies = [
        ('python_problems', '0019_language_solution'),
    ]

    operations = [
        migrations.RunPython(create_languages),
    ]
