FROM python:3.9-slim

# Create a working directory
WORKDIR /sandbox

# Copy the script to the working directory
COPY python_problems/static/python_problems/scripts.py /sandbox/scripts.py

# Command to execute the script
CMD ["python", "scripts.py"]
